### PR TITLE
Refactor project

### PR DESCRIPTION
**Pull request by ggouzi**
Proposal of refactoring:
- Update grafana dashboard to latest version + use timeseries chart instead of graph (old)
- Provision dashboard automatically: Fix for #4 
- Refactor architecture using dedicated folder for each component

### CODE REVIEW

**Comment by Kludex** [comment]
Thanks for the PR.

Can you also replace the image on the README, please?

**Comment by ggouzi** [comment]
Sure, done

**Comment by RoTorEx** [comment]
Thanks for your PR. It works!

**Comment by Kludex** [comment]
Thanks! 🙏

**Pull request merged**
